name: Test

on:
  pull_request:
  # allows this workflow to be reusable (e.g. by the build workflow)
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: save date
      run: |
        python -m pip install --upgrade pip setuptools
        pip install tox tox-gh-actions
        datethen=`date -d "-20 minutes" --utc +%FT%TZ`
        echo "datelimit=$datethen" >> $GITHUB_ENV
        echo $datethen

    - name: display
      env:
        COMMIT_DATE: ${{ github.event.base.repo.updated_at }}
      run: |
        echo ${COMMIT_DATE}
        echo ${datelimit}

    - name: Dump github context
      shell: bash
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
  
    - name: run tox
      if: github.event.base.repo.updated_at <= env.datelimit
      run: tox

    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: false
